DapperCollectives/CAST

- backend/main/community_test.go
- backend/main/community_user_test.go
- backend/main/test_utils/community_user_utils.go
- backend/main/test_utils/community_utils.go
With this new pattern there is some repeating code in the tests, for example when a communityStruct is created, then payload, then api call. As this code is repeating, is it useful to abstract it away into a reusable utils func?
> refactored community_user tests, added util funcs

- frontend/packages/client/src/components/CommunityProposalList.js
- frontend/packages/client/src/components/CommunityProposals.js
- frontend/packages/client/src/components/Dropdown.js
- frontend/packages/client/src/const/index.js
- frontend/packages/client/src/pages/Proposal.js
- Group active and pending proposals into one list 
- Group cancelled and closed proposals into one list
> feat(front): group proposals into two list when filter has "all" selected

- frontend/packages/client/src/components/ProposalsList/ProposalHeader.js
- when spinning up local dev, on closed proposals frontend is trying to fetch results. This will check if result object is coming empty which is causing the frontend to break.
> fix: add catch for empty result object

- frontend/packages/client/src/hooks/useUserRoleOnCommunity.js
- frontend/packages/client/src/pages/Proposal.js
This PR fixes showing the cancel button on proposals for ex-authors (after the user has left the community: all roles are removed when a user leaves the community). 
Before the check as done by looking if the user address was the same as the one that created the proposal. 
Since now we have roles in the community, only community authors should be able to chancel them. If the creator left the community, the user will need to rejoin and get an author role to be able to cancel a proposal
> fix(frontend): update role check for cancelling proposal

- backend/main/community_test.go
- backend/main/community_user_test.go
- backend/main/models/community_users.go
- backend/main/server/app.go
- backend/main/test_utils/community_utils.go
**Ticket:** [CAS-106](https://linear.app/dappercollectives/issue/CAS-106/get-community-users-by-type-api-endpoint)
- Fixes test for `/communities/[communityId]/users` endpoint
- Removes unused code block in `TestCreateCommunityUsers`
- Adds endpoint `/communities/[communityId]/users/type/[userType]`
- Adds tests for above endpoint
> CAS-106: Add Endpoint for query community users by userType

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Tablink.js
When hovering over items like Community Card (homepage), Back button, proposal card, etc the elements have a zoom effect. This PR removes that effect
> style(frontend): remove scale on elements

- frontend/packages/client/src/components/Community/CommunityEditorDetails.js
- frontend/packages/client/src/components/CommunityCreate/StepTwo.js
On community creation workflow, second step, autofocus is applied to last element on authors list. It should be applied to admins since it's the first input to complete that appears: 
Fixed: 
Next new inputs will have autofocus as the are added on the page
> fix(frontend): fix autofocus on author editor step

- backend/main/leaderboard_test.go
- backend/main/models/community_users.go
- backend/main/server/app.go
- backend/main/test_utils/community_utils.go
- frontend/packages/client/src/components/Community/CommunityEditorDetails.js
- frontend/packages/client/src/components/Community/CommunityEditorProfile.js
- frontend/packages/client/src/components/Community/JoinCommunityButton.js
- frontend/packages/client/src/components/Community/hooks/useLinkValidator.js
- frontend/packages/client/src/components/CommunityCreate/StepTwo.js
- frontend/packages/client/src/components/CommunityLinks.js
- frontend/packages/client/src/components/StepByStep/index.js
- frontend/packages/client/src/hooks/useCommunity.js
- frontend/packages/client/src/hooks/useCommunityUsers.js
- frontend/packages/client/src/pages/Community.js
> dev -> staging 

- frontend/packages/client/src/App.sass
Now it defaults to: `border-color: hsl(0deg, 0%, 71%);` from bulma config
https://user-images.githubusercontent.com/7526740/176703023-7393a415-a488-4cb1-9130-cdb0684b87c6.mov
> fix(frontend): remove yellow border on button hover

- backend/main/models/community.go
- backend/main/server/app.go
the avatar, or `Logo` field was being overwritten with `nil` on update if a value was not sent in the payload. This has been fixed by using the `COALESCE` keyword in the sql `UpdateCommunity` models function
> bugfix cas-168 update does not overwrite nil fields

- frontend/packages/client/src/contexts/Web3.js
- frontend/packages/client/src/pages/CommunityCreate.js
- frontend/packages/client/src/utils.js
Depends on #62 
Added validation for flow addresses, when creating a community it will show an error modal if any of the addresses used is not a valid flow addr. Maybe wording and some style will need to be added:
> CAS-108 - validate contract address during community creation

- frontend/packages/client/src/components/Community/CommunitiesPresenter.js
- frontend/packages/client/src/components/Community/CommunityCard.js
- frontend/packages/client/src/components/Community/CommunityEditorProfile.js
- frontend/packages/client/src/components/CommunityCreate/StepOne.js
- frontend/packages/client/src/hooks/useCommunity.js
- frontend/packages/client/src/hooks/useCommunityDetails.js
- frontend/packages/client/src/pages/Community.js
- frontend/packages/client/src/pages/Home.js
Update on community fields: 
community name => required
community Description => not required
logo => not required, defaults to `react-blockies`
community Terms => not required      
category => required
> CAS-169 - update fields validation on community creation

- frontend/packages/client/.env.example
- frontend/packages/client/package.json
- frontend/packages/client/src/App.js
- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/CommunitiesPresenter.js
- frontend/packages/client/src/contexts/ErrorHandler.js
- frontend/packages/client/src/hooks/useCommunity.js
- frontend/packages/client/src/hooks/useFeaturedCommunities.js
- frontend/packages/client/src/hooks/useUserCommunities.js
- frontend/packages/client/src/pages/CommunityCreate.js
- frontend/packages/client/src/pages/Home.js
- frontend/yarn.lock
Home page updates:
- Added `react-query`
- Remove redux dependencies not used 
- Moved some `dependencies` to `dev dependencies` 
There's only one issue that will be addressed in another PR:
1. User clicks on join in a community in the home page from the feature communities section
2. If the "My Communities" section was not visible it should appear with the community the user has just joined. Same if the user leaves the community and that was the only one, the "My Communities"  section should fade out
> CAS-154 - add My Communities section to homepage

- frontend/packages/client/src/components/Message.js
- frontend/packages/client/src/pages/Home.js
> cas-209 - Update version message on landing page

- frontend/packages/client/src/components/Community/CommunityCard.js
- frontend/packages/client/src/pages/Community.js
Change the order of the community page navigation to:
- Proposals
- Members
- About
Also changes the default tab to be "proposals" when none is provided, as well as making CommunityCard default to `proposals`
> rearrange community page tab order and set default tab to proposals

- frontend/packages/client/src/pages/Community.js
**Ticket:** [CAS-122](https://linear.app/dappercollectives/issue/CAS-122/non-square-images-for-community-avatar)
Changes the logo handling to be a background image on a div, so image dimensions don't matter. Image positioning will be centered on div.
> CAS-122: Fix community banner image to support non-square images

- backend/main/models/proposal.go
- backend/main/proposal_test.go
- backend/main/server/app.go
In Production environment only we need to increase the time a proposal can go live to 1 hour after the current time for proposals. 
This should be reflected in the frontend UI and also validated on the backend as well. The reason for this change is because the snapshotter tool will need time to run and capture the chain so we know which accounts had the correct balance at the time the proposal was created:
• Adds SetStatus method on `createProposal` and `getProposal` controllers
• Checks if grace period has passed, only if strategy has a contract and environment is prod. Grace period is one hour
> cas-107 / 156 Increase time before proposals can start

- backend/migrations/000021_add_achievements_details_column.down.sql
- backend/migrations/000021_add_achievements_details_column.up.sql
removes duplicated migration file:
`error: duplicate migration file: 000021_add_balance_of_nfts.down.sql`
> remove duplicated migration files

- frontend/packages/client/src/components/Community/CommunityEditorLinks.js
- frontend/packages/client/src/components/Community/hooks/useLinkValidator.js
> CAS-187 - add helper text to Community Links

- frontend/packages/client/src/components/Community/CommunityCard.js
- frontend/packages/client/src/components/Community/JoinCommunityButton.js
Applied style fixes for join community button, also avatar size was changed on mobile and some styling on community card based on CAS-103 feedback.
Before: 
After:
> CAS-103 - fix join button position

- frontend/packages/client/src/pages/Community.js
remove `Founded 2022` from community pages and additionally only show the `<hr>` that was above it if we're showing edit buttons
> remove Founded 2022 from community pages

- backend/main/leaderboard_test.go
- backend/main/models/community_users.go
- backend/main/test_utils/community_utils.go
- frontend/packages/client/src/api/constants.js
- frontend/packages/client/src/api/leaderboard.js
- frontend/packages/client/src/components/LeaderBoard.js
- frontend/packages/client/src/hooks/useLeaderBoard.js
- frontend/packages/client/src/pages/Community.js
**Ticket:** [CAS-177](https://linear.app/dappercollectives/issue/CAS-177/add-leaderboard-score-to-community-member-page)
**Description**
Connects Leaderboard API with the Leaderboard component on the community page
NOTE: Added a pattern to separate the API logic from the useQuery hook. This promotes reusability of the api logic, and simplifies the fetching hooks so that the only logic relates to the hook, and not to the fetching.
> CAS-177: Integrate Leaderboard API with front-end

- frontend/packages/client/src/pages/Home.js
> CAS-227 - Update text link

- frontend/packages/client/src/components/StepByStep/index.js
- frontend/packages/client/src/pages/CommunityCreate.js
the colors for the steps while creating a community should be the same as when creating a proposal. this PR removes the customization option of the step colors in StepByStep to make them consistent across all uses
> make create community steps the same color scheme as create proposal

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/CommunityCard.js
- frontend/packages/client/src/components/Community/CommunityEditorProfile.js
- frontend/packages/client/src/components/CommunityCreate/StepOne.js
- adds a `line-clamp` rule to the community titles so they dont go over 2 lines of text
- adds 50 character `maxLength` to title input
Relies on https://github.com/DapperCollectives/CAST/pull/145
> fix overflowing community titles and cap title input to 50 characters

- backend/main/leaderboard_test.go
- backend/main/models/community_users.go
- backend/main/server/app.go
- backend/main/test_utils/community_utils.go
- backend/migrations/000025_rename_achievements_sequence.down.sql
- backend/migrations/000025_rename_achievements_sequence.up.sql
- frontend/packages/client/src/api/leaderboard.js
- frontend/packages/client/src/components/LeaderBoard.js
- frontend/packages/client/src/hooks/useLeaderBoard.js
* CAS-177: Integrate Leaderboard API with front-end
* CAS-177: Fix bug in leaderboard paging
* CAS-177: Add pageSize to fetchLeaderboard
* CAS-177: Fix stlying for score
* CAS-229: Add Current User to leaderboard
* CAS-229: Fix broken proposal test
* CAS-229: Rename achievements sequence table
* CAS-229: Rename data.leaderboard to data.users
* CAS-229: Update leaderboard api json
* CAS-229: Resequence migration files
* CAS-229: Resequence migration files
Co-authored-by: Jonathan <jon.bluks@gmail.com>
> Main -> Staging

- frontend/packages/client/src/components/UploadImageModal.js
- frontend/packages/client/src/const/index.js
Added Error Message on upload:
Not Related but fixes style on mobile:
Before:
After:
> CAS-248 - add error message for in-line image

- frontend/packages/client/src/components/ProposalInformation.js
- frontend/packages/client/src/components/StrategyModal.js
- frontend/packages/client/src/pages/Proposal.js
> cas-134 Display proposal strategy name instead of icon

- backend/migrations/000026_update_voting_strategy_desc.down.sql
- backend/migrations/000026_update_voting_strategy_desc.up.sql
Migration to update strategy description text
> CAS-262 - Add migration file to update text

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Tablink.js
- frontend/packages/client/src/pages/Community.js
Animates the "active" underline underneath a navigation tab on the community page similar to https://codepen.io/everdimension/pen/xZLggo but with support for dynamic tab link widths / positions.
> animate active bar under community tab links

- backend/main/community_user_test.go
**Ticket:** [CAS-281](https://linear.app/dappercollectives/issue/CAS-281/failing-test-on-main-branch)
- order of values returned for roles in TestGetUserCommunities is not consistent, sorted values to ensure test passes while checking for expected roles.
> CAS-281: Fix broken test

- frontend/packages/client/src/components/ProposalInformation.js
Shrink author address to fit in container:
https://user-images.githubusercontent.com/7526740/180472627-c0c70a68-a512-4865-8b25-94445d78f0ab.mov
> cas-298 - add component and ref to calculate width

- frontend/packages/client/src/components/LeaderBoard.js
if the currently connected user exists in the leaderboard, don't render them twice and instead highlight their spot on the leaderboard with a black background version of their position
> dont list user twice if theyre on leaderboard

- frontend/packages/client/src/components/Community/StrategyEditorModal/StrategyInformationForm.js
- frontend/packages/client/src/components/Community/StrategyEditorModal/index.js
**Ticket:** [CAS-291](https://linear.app/dappercollectives/issue/CAS-291/update-strategy-selector-modal-step)
- Adds Strategy name to the title of the information modal.
- Adds text for linking to Getting Started guide. Temporarily links to https://docs.cast.fyi since Getting Started Guide is not completed yet.
> CAS-291: Add Link to getting started guide on Strategy Selector

- backend/main/server/app.go
- backend/main/strategies/balance_of_nfts.go
- backend/main/strategies/one_address_one_vote.go
- backend/main/strategies/staked_token_weighted_default.go
- backend/main/strategies/token_weighted_default.go
- backend/main/strategies/utils.go
- backend/main/strategies_test.go
- backend/migrations/000029_add_one_address_nft_ft_strategy.down.sql
- backend/migrations/000029_add_one_address_nft_ft_strategy.up.sql
- frontend/packages/client/src/components/Community/StrategyEditorModal/index.js
- frontend/packages/client/src/hooks/useVotingStrategies.js
* updated makeFile and flow.json
* updated float import paths
* updated flow nft contracts
* updated flow nfts contracts to latest versions
* CAS-204: Add FE changes for One Address One Vote information
* CAS-204: Add BE changes for One Address One Vote restrictions
* updated the ExampleNFT flow to run successfuly on emulator
* fixed issue with GetVoteWeightForBalance balance_of_nfts
* added flow contracts and updated Makefile
* updated cadence script for new ExampleNFT
* created processThreshold logic
* updated NFT ID to type interface to handle string or uint
* clean up
* handle nft balance return type in EnforceToken
* overflow breaking changes fixes
* added in wrongly deleted make command
* updated NFT Test
* updated Makefile
* CAS-204: Add NFT/FT restrictions to One Address One Vote …
> Main -> Staging (One Address One Vote)

- frontend/packages/client/src/components/WalletConnectModal.js
- frontend/packages/client/src/const/index.js
- frontend/packages/client/src/contexts/Web3.js
- frontend/packages/client/src/networks.js
On local dev, when using new modal  to connect to dev wallet frontend takes staging configuration for `walletDiscoveryApi` using the call `fcl.discovery.authn.subscribe` then it tries to connect to testnet. 
This PR removes the parameter `{ service }` from the call `injectedProvider.authenticate` to connect by default to local emulator instead of testnet.
> add configuration to use local emulator

- frontend/packages/client/src/components/Community/StrategySelectorForm.js
- frontend/packages/client/src/components/CommunityCreate/StepFour.js
- frontend/packages/client/src/pages/CommunityEditor.js
- Fix loader position on edit community
- Allow to delete strategy on community creation when there is only one strategy. In case the information entered for the strategy is not valid, user needs to be able to delete the existing one to be able to add it again to fix the strategy data entered.
> fix strategy update on community creation

- backend/main/community_test.go
- backend/main/list_test.go
- backend/main/models/community_users.go
- backend/main/proposal_test.go
- backend/main/strategies_test.go
- backend/main/vote_test.go
**Ticket:** [CAS-345](https://linear.app/dappercollectives/issue/CAS-345/when-viewing-a-proposal-page-im-seeing-the-cancel-proposal-button-when)
Query for returning merging roles in Community was incorrect. Fixed to Query the DB for all user communities, then merge multiple communities into 1 with list of unique roles.
Note: Also fixes some broken test based on string changes
> CAS-345: Fix UserCommunities query to return proper roles

- frontend/packages/client/src/components/LeaderBoard.js
**Ticket:** [CAS-358](https://linear.app/dappercollectives/issue/CAS-358/all-voters-displayed-as-current-user-on-leaderboard)
- UI Logic was incorrectly showing all users as current user. Updated to only highlight the current user if they are on the leaderboard.
> CAS-358: Fix leaderboard showing all accounts as connected account

- backend/main/models/balance.go
- backend/main/models/proposal.go
- backend/main/server/app.go
- backend/main/shared/snapshot-flow.go
- backend/main/shared/structs.go
- backend/main/strategies/staked_token_weighted_default.go
- backend/main/strategies/token_weighted_default.go
This PR fixes two issues. 
- `EnforceMaxWeight` was not comparing balance against `proposal.Max_weight` correctly 
- Local dev was not updating balances to the DB because of snapshot balance fetch override. 
Changes made
• Adds new algorithm to convert balances of `uint64` to float, with the correct decimal place shifts
* Sends back a dummy balance on `FetchBalanceFromSnapshot`, 
* Adds new function inside `token-weighted-default` and `staked-token-weighted-default`, `FetchBalanceFromSnapshot`, this cleans up `FetchBalance` quite a lot. 
* Moves `FTBalanceResponse` Struct into shared. 
* Uses that same struct for both FT and Flow Token responses from snapshotter
* Adds constructor `NewFTBalance()`, this is required if you want to update a struct by reference within another function, its …
> dev environment + results fix

- backend/main/models/community_users.go
**Ticket:** [CAS-395](https://linear.app/dappercollectives/issue/CAS-395/update-leaderboard-response-payload)
- Previously, totalUsers may have been returning an extra user in the count. Updated totalUsers to be the length of the leaderboard users, or count if leaderboard length is greater than count.
> CAS-395: Fix total users to match length of leaderboard or count

- backend/main/leaderboard_test.go
- backend/main/models/community_users.go
- backend/main/models/proposal.go
- backend/main/models/vote.go
- backend/migrations/000033_alter_votes_table.down.sql
- backend/migrations/000033_alter_votes_table.up.sql
**Ticket:** [CAS-393](https://linear.app/dappercollectives/issue/CAS-393/leaderboard-score-preserved-for-cancelled-proposals)
For the leaderboard, votes and achievements were being counted for cancelled proposals. Adds a helper function to clean up records in `votes` and `user_achievements` table when a proposal is cancelled.
> CAS-393: Handle voting and achievements for cancelled proposals

- backend/main/shared/ipfs.go
• adds `bypass` method on ipfs client. This is to stop the flaky ipfs responses I've been getting on various wifis.
> cas-404 bypass ipfs with dummy vals for local dev 

- backend/main/shared/structs.go
the fields of `ftBalance` Struct, which gets updated from the snapshotter, was not being initialized in staging / prod. This is a fix that adds 0 vals, these vals get overridden when the snapshotter returns. 
If these fields are left uninitialized, the function `GetAddressBalanceAtBlockHeight` cannot update `ftBalance` by reference.
> hotfix added initialization if not in local dev

- backend/main/models/community.go
- backend/main/server/controllers.go
- backend/main/server/helpers.go
- backend/migrations/000034_alter_communities_table.down.sql
- backend/migrations/000034_alter_communities_table.up.sql
- frontend/packages/client/src/components/Community/CommunityEditorProfile/ProfileForm.js
- frontend/packages/client/src/components/Community/ProposalThresholdEditor/FormConfig.js
- frontend/packages/client/src/components/Community/ProposalThresholdEditor/ProposalThresholdEditor.js
- frontend/packages/client/src/components/Community/ProposalThresholdEditor/ThresholdForm.js
- frontend/packages/client/src/components/CommunityCreate/StepThree.js
- frontend/packages/client/src/hooks/useCommunity.js
- Adds a Contract Type field to the Community Proposal Page. This will allow the backend to choose the right cadence script when validating proposal creation
- Adds `Contract_type` to the `communities` table to track the contract type for proposal creation.
- If a user attempt to create a proposal without matching the specified threshold for proposal creation, they will get a 403 error.
e
NOTE: This fix should also address: [CAS-435](https://linear.app/dappercollectives/issue/CAS-435)
> CAS-427: Fix Proposal restriction using NFT Contract

- frontend/packages/client/src/components/Community/CommunityEditorProfile/ProfileForm.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/ImageChoiceUploader.js
- frontend/packages/client/src/components/UploadImageModal.js
Based on this [issue](https://github.com/react-dropzone/react-dropzone/issues/1222) opened on the [react-dropzone](https://react-dropzone.js.org/) GitHub [repo](https://github.com/react-dropzone/)  setting `useFsAccessApi` to `false` makes the file explorer to open when clicking on the button
> CAS-405 - Fix to open file explorer when uploading images

- backend/main/models/community.go
- backend/main/test_utils/community_utils.go
- The Only update by designated author field is not updated when editing a community
- Value was not being passed to updateCommunity and part of the UPDATE query.
> CAS-434: Fix Only Author submit not stored in DB

- backend/Makefile
- backend/main/cadence/float/transactions/create_group.cdc
This PR adds a new make command `make float` this adds one FLOAT nft into the admin local emulator wallet address `0xf8d6e0586b0a20c7`
If we need to test float functionality locally in the emulator its now possible by running this command. 
N.B if you've already ran `make nft` you'll have to quit the emulator then run `make float` as both commands deploy some of the same dependancy contracts to the same address.  `make float` internally calls `make nft`
> cas 425 `make float` so that we can test float on local dev

- backend/main/server/app.go
*adds port flag definition in `Initialize`
after other flags were defined, in staging we were seeing the error
```
11:50PM INF Log level: DEBUG for APP_ENV=PRODUCTION
flag provided but not defined: -port
Usage of /flow-voting-tool/flow-voting-tool-server:
-amount int
Amount of proposals to create (default 4)
-db string
database type
flag provided but not defined: -port
```
The port flag is not used in the Makefile but it is used inside out Dockerfile. Hoping this will fix it!
**General Note**
How `flat.Int()` works : 
```
func flag.Int(name string, value int, usage string) *int
Int defines an int flag with specified name, default value, and usage string.
The return value is the address of an int variable that stores the value of the flag.
flag.Int on pkg.go.dev
```
Flags need to be …
> hotfix staging - added port flag definition

- backend/flow.json
- backend/main/cadence/scripts/custom/get_nba_topshot.cdc
- backend/main/shared/flow.go
•adds in contract address replace code, all the addresses for each environment are in the `flow.json`. tested locally and the addresses are being replaced correctly.
> adds in contract replace code for topshot Addr

- frontend/packages/client/src/components/Proposal/VoteOptions.js
- frontend/packages/client/src/pages/Proposal.js
previously we didnt let people interact with the VoteOptions component if they werent logged in, now we will but prompt them to connect before they can actually cast their vote
> allow unconnected user to vote, then prompt wallet connect

- frontend/packages/client/src/pages/CommunityCreate.js
- Fix to hide next button on community creation
> remove next button

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/CommunityEditorDetails/FormFields.js
- frontend/packages/client/src/components/Community/CommunityEditorLinks/FormFields.js
- frontend/packages/client/src/components/Community/CommunityPropsAndVoting.js
- frontend/packages/client/src/components/Community/StrategySelectorForm.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/ImageChoiceUploader.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/ImageChoices.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/TextBasedChoices.js
- frontend/packages/client/src/components/ProposalCreate/StepTwo/StepTwo.js
- frontend/packages/client/src/components/UploadImageModal.js
- frontend/packages/client/src/components/common/Checkbox.js
- frontend/packages/client/src/components/common/CustomDatePicker.js
- frontend/packages/client/src/components/common/Dropdown.js
- frontend/packages/client/src/components/common/Editor/DraftjsEditor.js
- frontend/packages/client/src/components/common/Editor/Editor.js
- frontend/packages/client/src/components/common/Input.js
- frontend/packages/client/src/components/common/TextArea.js
- frontend/packages/client/src/contexts/ErrorHandler.js
- frontend/packages/client/src/index.css
- frontend/packages/client/src/pages/CommunityCreate.js
- frontend/packages/client/src/pages/Proposal.js
- remove Arimo/Roboto/Helvetica, make DM Sans the primary font for everything
- refactor color variables, remove unused variables and add "success" and "danger" color for success/error messages
- switch any `gray` classes to `grey` as Bulma uses `grey` convention, refactor grey classes to be simpler
- update some of our grey shades
- remove `$red` and `.has-text-red` as we were using it exclusively for error messages, which in that case we should actually use Bulma's `$danger` and `has-text-danger`
> update global styles / classes

- frontend/Dockerfile.stage
- frontend/deploy/nginx.conf
- frontend/packages/client/public/index.html
Docker images require references of `cast.png` to be updated to `cast.jpg`
> Hotfix: rename cast.png references to .jpg

- frontend/Dockerfile.stage
- frontend/deploy/nginx.conf
- frontend/packages/client/public/index.html
- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/CommunitiesPresenter.js
- frontend/packages/client/src/components/Header.js
- frontend/packages/client/src/components/HomeFooter.js
- frontend/packages/client/src/components/HomeHeader.js
- frontend/packages/client/src/components/Label.js
- frontend/packages/client/src/components/Message.js
- frontend/packages/client/src/components/Svg.js
- frontend/packages/client/src/components/TooltipMessage.js
- frontend/packages/client/src/components/WalletConnect.js
- frontend/packages/client/src/pages/About.js
- frontend/packages/client/src/pages/Home.js
Hotfix to update references to `cast.png` to `cast.jpg`
> Main -> Staging 

- frontend/packages/client/src/components/WalletConnectModal.js
- If Lilico extension is not installed then the icon does not render correctly.
> fix Lilico icon 

- frontend/packages/client/src/components/Community/CommunityCard.js
simplify the styles for the container of the watch eye icon that it properly wraps on both desktop and mobile
> fix mobile styling for watch icon

- frontend/packages/client/src/hooks/useCommunityMutation.js
- api request from client was not sending the proper payload with timestamp hexified
> Fix payload missing hexified timestamp

- frontend/packages/shared-components/src/Svg/Logo.js
fixes issue where header logo is cut off on some browsers
> fix cut off logo in some browsers

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/CommunityEditorDetails/FormFields.js
- frontend/packages/client/src/components/Community/StrategySelectorInput.js
> CAS-539 - style fix on strategy selector

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/ProposalCreate/StepTwo/TimeIntervals.js
To test this PR:
- update your machine time to be within the last hour of today
- Create a proposal and select start time of proposal to be tomorrow
- On drop down time for startTime you'll see first minutes interval of the day removed to meet the one hour requirement between time now and start of proposal.
> CAS-532 - Fix start time interval

- frontend/packages/client/src/App.sass
this tooltip is getting cut off on mobile where it shouldn't exist anyway since there is no hover state there
> only include hover cta on desktop

- frontend/packages/client/src/components/Community/CommunityCard.js
- frontend/packages/client/src/components/Community/JoinCommunityButton.js
Fixes horizontal scrolling on mobile by removing a span element on mobile. This is used for showing a tooltip on desktop.
> CAS-581: Hide tooltip in join button on mobile

- backend/main/server/controllers.go
- backend/main/server/helpers.go
- backend/tests/main_test.go
- backend/tests/proposal_test.go
•Adds new `errorResponse : errStrategyNotFound`
•Changes return type of `createProposal` for better error handling.
> cas-577 catch strategy name errors. update tests

- backend/main/models/community.go
- backend/main/server/controllers.go
- backend/main/server/helpers.go
- backend/main/shared/flow.go
- backend/tests/community_test.go
**Description**
- createProposal error contains reason for failure, if it is a permissions issue
- adds more context + `reason` message to canUserCreateProposal endpoint
- refactors functions to be more re-usable
- adds additional assertions in tests for reason user doesn't have permission to create proposal
**Demo**
`make test`
> CAS-594: Return reason if create proposal fails

- frontend/packages/client/src/components/Proposal/HeaderNavigation.js
- frontend/packages/client/src/components/Proposal/ShareDropdown.js
- frontend/packages/client/src/pages/Proposal.js
Creates an additional message that is generic this scenarios:
'Check out <proposal name> on CAST![[proposalURL]]'.
- User without a connected wallet sharing the proposal over twitter
- User sharing an upcoming, closed or cancelled proposal over twiter
- User with a connected wallet sharing a proposal they did not vote on
> CAS-636: Update Twitter message

- frontend/.gitignore
- frontend/packages/client/.env.development
- frontend/packages/client/package.json
- frontend/packages/client/src/App.js
- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/common/Toast.js
- frontend/packages/client/src/hooks/useToast.js
- frontend/yarn.lock
- adds `@chakra-ui/react` and its dependencies
- create `useToastHook` that wraps around chakra's `useToast` to render a custom "CAST" style toast design
```js
const { popToast } = useToast();
// ....
popToast("My toast message", {
footerText: "My toast link", // optional
footerLink: "/my-path", // optional ,only used with footerText
});
```
originally opened this PR against notifications branch but we want this sooner than later so re-opened against 1.6, see my original comments here
https://github.com/DapperCollectives/CAST/pull/655
> VSL-245 - add chakra ui + toast component

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Proposal/VoteOptions/PostVoteOptions.js
- frontend/packages/client/src/components/Proposal/VoteOptions/VoteOptions.js
- frontend/packages/client/src/components/index.js
builds upon https://github.com/DapperCollectives/CAST/pull/632 and adds a `PostVoteOptions` component that is to be shown after a user has voted. note that the twitter button doesnt work at the moment as it will be implemented in a follow up PR/ticket
> VSL-241 - add PostVoteOptions after voting on proposal

- frontend/packages/client/src/api/proposals.js
The update proposal payload was incorrect and did not provide the payload field containing the updated status.
I am not sure if the fix I made is the correct fix, but it works now. Assuming it worked before, so not sure whether the back-end was updated and that broke it, or the front-end.
> CAS-673: Fix update proposal payload

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/CommunityEditorProfile/FormFields.js
- frontend/packages/client/src/components/Community/ProposalThresholdEditor/ThresholdForm.js
- frontend/packages/client/src/components/Community/StrategyEditorModal/CustomScriptSelector.js
- frontend/packages/client/src/components/Community/StrategyEditorModal/StrategyInformationForm.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/index.js
- frontend/packages/client/src/components/ProposalCreate/StepTwo/StepTwo.js
- frontend/packages/client/src/components/common/Input.js
- standardized input classnames that were used in every instance of `Input`: `rounded-sm border-light p-3 column is-full`
-  default to `border-light` unless there is an error in which case use `border-danger`
> manny/vsl-264: standardize input and add red color to border

- frontend/packages/client/src/components/ProposalCreate/StepOne/index.js
- frontend/packages/client/src/components/ProposalCreate/StepThree/StepThree.js
- frontend/packages/client/src/components/ProposalCreate/StepTwo/StepTwo.js
Some field arrays are not validated onChange mode, this enables next button to trigger validation. This happens when switching from/to ranked-vote-choice single choice
> CAS-674: Enable next button on form with dirty field status

- frontend/packages/client/src/components/ProposalCreate/StepThree/TimeIntervals.js
- Next nearest start time in production is now 10 minutes, before it was 60 mins
> CAS-700: Make start time wait to be 10 mins

- frontend/packages/client/src/components/ProposalCreate/StepTwo/StepTwo.js
- When navigating between proposal creation stages (via the 'Back' and 'Next' buttons), the data voting option entered is cleared.
> CAS-696: fix voting option 
