DapperCollectives/CAST

- frontend/packages/client/src/components/StepByStep/StepByStep.sass
- frontend/packages/client/src/components/StepByStep/index.js
> cas-60 Make process tracker in left column sticky

- frontend/packages/client/src/components/ProposalCreate/StepOne/TextBasedChoices.js
- frontend/packages/client/src/utils.js
Bug: On the create proposal page when you click Visual then click Text-based the UI will display 2 empty text choices
> Fix toggle of Proposal Choice

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/ProposalCreate/StepOne/index.js
- frontend/packages/client/src/components/Svg.js
- frontend/packages/client/src/components/UploadImageModal.js
- frontend/packages/client/src/components/index.js
> feat(front): add inline images

- frontend/packages/client/src/components/CommunityProposalList.js
- frontend/packages/client/src/components/CommunityProposals.js
Needs https://github.com/DapperCollectives/CAST/pull/24 merged before
Added empty placeholder:
> feat(cas-72): add empty state on community proposal

- backend/go.mod
> go 1.16 -> 1.17

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/ProposalCard/ProposalCardHeader.js
- frontend/packages/client/src/components/TableMembers.js
- frontend/packages/client/src/pages/Community.js
style fixes and blockies style updates
> style(frontend): update classes for title and blockies

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/CommunityEditorDetails.js
- Based on this PR currently opened on Bulma's repo, this PR adds helpers for spacing based on view port size. 
https://github.com/jgthms/bulma/pull/3184
It's been opened for a while, and this functionality would help ups to reduce the use of media queries and extra classes to know the screen size to apply spacing.
> feat: add responsive spacing helpers

- frontend/packages/client/src/components/Community/CommunityCard.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/TextBasedChoices.js
Make Add button click area sorter: 
Before:
After:
> fix: add button click area to be sorter

- backend/main/shared/flow.go
• fixes flow path issue on main!
> fix for flow path

- frontend/packages/client/src/pages/Community.js
> fix(frontend): add button community settings  on mobile

- backend/main/community_user_test.go
- backend/main/leaderboard_test.go
- backend/main/models/community_users.go
- backend/main/server/app.go
- backend/main/test_utils/community_utils.go
**Ticket:** [CAS-135](https://linear.app/dappercollectives/issue/CAS-135/leaderbord-backend-v0)
**Description**
- Adds endpoint `/communities/:communityId/leaderboard` 
- Returns list of user addresses and score based on tallying votes on all proposals
> CAS-135: Add Leaderboard Endpoint

- frontend/packages/client/src/components/Community/CommunityEditorProfile.js
- frontend/packages/client/src/components/Community/hooks/useLinkValidator.js
- Fixes button to save after updating community name or logo
- Also update discord regular expression
> fix(frontend): update edit community form validation

- .github/workflows/update-prod.yaml
> PUSH TO PROD

- .github/workflows/update-prod.yaml
> Staging to PROD GCP

- backend/migrations/000020_add_balance_of_nfts.down.sql
- backend/migrations/000020_add_balance_of_nfts.up.sql
• creates new migration for `balance-of-nfts` strategy
> added nft strategy to DB, created new migration

- frontend/packages/client/src/components/CommunityCreate/StepThree.js
- frontend/packages/client/src/hooks/useCommunity.js
…(#96)
* update condition
* add comment
* update condition
* update functions
* update function name
* fix typo
* update order
Co-authored-by: David Slone <dbslone@gmail.com>
> Main -> Staging

- frontend/packages/cadence/package.json
- frontend/packages/client/src/pages/CommunityCreate.js
Local emulator must be started using the backend flow file, otherwise contracts and other definitions won't be loaded into the emulator
- Updated yarn start script on frontend folder to start flow emulator with backend config
> CAS-182 - fix validation for flow addresses

- frontend/packages/client/src/components/CommunityCreate/StepTwo.js
> CAS-183 - Remove reference to domain names in community creation flow

- frontend/packages/client/src/components/CommunityCreate/StepOne.js
- frontend/packages/client/src/hooks/useCommunity.js
Fix loading default value in dropdown component on community creation when user presses back button.
> CAS-205 - fix loading category when pressing back during create community

- frontend/packages/client/src/components/ProposalInformation.js
See: https://linear.app/dappercollectives/issue/CAS-82#comment-a51b2e81
> cas-82 Update proposal result text to left-align

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/CommunitiesPresenter.js
- frontend/packages/client/src/components/Community/CommunityCard.js
- frontend/packages/client/src/components/Community/JoinCommunityButton.js
- Added Missing "about" sub-header: this still has an issue with positioning button that it's being handled in another issue- 
- Fixed Button shape (rectangle vs. oval) and color (black vs. white):
Community title fixes:
Font weight feels heavier on staging
Title (+ subhead) center aligned to logo vs. top aligned
Before:
After:
> CAS-191 - Homepage Community Component Updates

- frontend/packages/client/src/components/Community/CommunityEditorLinks.js
> fix input prop

- frontend/packages/client/src/components/Community/CommunityEditorProfile.js
- frontend/packages/client/src/components/CommunityCreate/StepOne.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/ImageChoiceUploader.js
- frontend/packages/client/src/const/index.js
- impose 2MB limit for avatars
- update max file size error message everywhere its used
- update image type error message to match sentence case
> update avatar max size and standardize error message language

- backend/main/proposal_test.go
- backend/main/strategies/one_address_one_vote.go
- backend/main/strategies/staked_token_weighted_default.go
- backend/main/strategies/token_weighted_default.go
this fixes as an issue which has been handled in cas-172, but this branch is not merged to main yet. There is a function that wrongly will throw an error if no user exists. This doesn't happen on dev, as service account exists.
> removed wrong error handle and old balance function

- backend/migrations/000024_change)strategy_flow_community.down.sql
- backend/migrations/000024_change_strategy_flow_community.up.sql
•adds new migration to fix the issue on `http://localhost:5001/proposals/1`, this fixes the issue for me locally.
> added new migration, 

- frontend/Dockerfile
- frontend/Dockerfile.stage
- Upgrade alpine version 16.3.0
- Using yarn to build front end and using workspace build command
- Copying yarn.lock file
> update docker config

- frontend/packages/client/public/index.html
- Disable browser zoom when user taps into fields on mobile
> CAS-278 - Disable zoom effect when using form fields

- frontend/Dockerfile
- frontend/Dockerfile.stage
- frontend/packages/client/.env.example
- frontend/packages/client/src/pages/CommunityCreate.js
> fix environment variable

- frontend/packages/client/src/components/CommunityCreate/StepThree.js
> cas-318 - Update copy for Proposal Threshold component

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/WalletConnect.js
https://user-images.githubusercontent.com/7526740/180478614-030bea36-d052-4413-b965-8309fe689929.mov
> cas-328 - Adjust main header spacing

- backend/Dockerfile
* updates snapshot base url to internal gcp
* http
> Jackson/update snapshotter to internal (#242)

- backend/Dockerfile
Co-authored-by: Fernando Sanchez <fer@Fernandos-MacBook-Pro.local>
> Added the port (#244)

- frontend/packages/client/src/components/Community/CommunityPropsAndVoting.js
- frontend/packages/client/src/pages/CommunityEditor.js
**Ticket:** [CAS-276](https://linear.app/dappercollectives/issue/CAS-276/validate-contract-address-storage-path-when-updating-community)
- Add check to Community Edit for contract addresses when adding new proposal strategies
> CAS-276: Validate contract address when updating community proposals

- frontend/packages/client/src/components/CommunityMembersList.js
**Ticket:** [CAS-337](https://linear.app/dappercollectives/issue/CAS-337/add-descriptive-text-to-members-page)
> CAS-337: Add descriptive text to members list

- backend/migrations/000028_update_voting_strategies_table.down.sql
- backend/migrations/000028_update_voting_strategies_table.up.sql
- frontend/packages/client/src/components/Community/StrategyEditorModal/StrategySelector.js
- frontend/packages/client/src/components/Community/StrategyEditorModal/index.js
**Ticket:** [CAS-317](https://linear.app/dappercollectives/issue/CAS-317/update-strategy-titles-and-descriptions-in-selector-modal)
> CAS-317: Update strategy names and definitions

- backend/Dockerfile
- frontend/packages/client/src/components/Community/JoinCommunityButton.js
- frontend/packages/client/src/components/HomeFooter.js
- frontend/packages/client/src/components/Svg.js
- frontend/packages/client/src/components/WalletConnect.js
- frontend/packages/client/src/components/WalletConnectModal.js
- frontend/packages/client/src/components/index.js
- frontend/packages/client/src/contexts/Web3.js
- frontend/packages/client/src/networks.js
Adds custom modal for connecting to a wallet:
> cas 333 - Custom Modal to connect to Wallet

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Label.js
- frontend/packages/client/src/components/Message.js
- frontend/packages/client/src/components/ModalAboutItem.js
- frontend/packages/client/src/components/Svg.js
- frontend/packages/client/src/components/WalletConnectModal.js
- frontend/packages/client/src/components/index.js
- frontend/packages/client/src/pages/About.js
Mobile:
Note: disregard separator below beta label, appears when inspecting but is not showing on regular view
> cas 295 - update about modal

- frontend/packages/client/src/components/CommunityHeader.js
- frontend/packages/client/src/pages/Community.js
- while loading avatar, bloquies was rendering without a `seed` prop
> hide avatar while loading

- frontend/packages/client/src/pages/CommunityCreate.js
- frontend/packages/client/src/pages/ProposalCreate.js
Fixes opening custom wallet connect modal and closes connect to wallet error message
> update modal to open custom modal wallet

- frontend/packages/client/src/components/Community/CommunityEditorProfile.js
- frontend/packages/client/src/components/CommunityCreate/StepOne.js
- frontend/packages/client/src/const/index.js
- frontend/packages/client/src/utils.js
- Add error validation  on description field and name for creating and editing a community
> fix validation on description and name field

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/HomeHeader.js
make fade in stars (without fadeout)
> update home animation 

- backend/main/strategies/token_weighted_default.go
save balance correctly for token-weighted-default strategy if using FlowToken
> HOTFIX: FlowToken using token-weighted-default strategy

- frontend/packages/client/src/App.sass
make stars animation to fade in faster
> update animation time

- frontend/packages/client/src/components/HomeHeader.js
- frontend/packages/client/src/components/WalletConnectModal.js
- frontend/packages/client/src/hooks/useStarAnimation.js
- frontend/packages/client/src/pages/About.js
Fixes horizontal scroll 
https://user-images.githubusercontent.com/7526740/181140302-67e19548-da8d-468f-ad18-dd32cb96e3b6.MP4
Also fixes border on connect modal on mobile:
after:
> style updates

- frontend/packages/client/package.json
- frontend/packages/client/public/manifest.json
- frontend/packages/client/src/components/WalletConnectModal.js
- frontend/packages/client/src/contexts/Web3.js
- frontend/yarn.lock
Adding Lilico to wallet modal: 
Question: should they be sorted in alphabetical order?
> cas 371 - Display Lilico in wallet connect modal

- frontend/Dockerfile.stage
- frontend/deploy/nginx.conf
Co-authored-by: Fernando Sanchez <fer@iMac-de-Fernando.local>
> Nginx change (#329)

- backend/main/strategies/staked_token_weighted_default.go
•fixes bug where staked strategy results/ endpoint was not being totalled correctly
> fixed pointer nil bug in staked strat

- backend/main/models/community.go
- backend/main/models/community_users.go
- backend/main/models/proposal.go
- backend/main/models/vote.go
- backend/main/server/controllers.go
- backend/main/server/helpers.go
- backend/main/shared/structs.go
no ticket for this one. 
• Continues refactor work in `helpers.go` to make functions more SRP (single-responsibility-principle) and therefore, shorter and more approachable. 
• uses `orderedParams` struct in a more efficient manner, reduces amount of params on several models methods.
> refactor helpers

- backend/main/models/community.go
• updates model function and struct
> cas-424 adds backend support for updating community threshold

- backend/main/models/vote.go
**Ticket:** [CAS-416](https://linear.app/dappercollectives/issue/CAS-416/float-strategy-voting-results-not-calculation-correctly)
**Description**
- Fixes FLOAT NFTs not showing vote results due to `getUsersNFTs()` not getting called
> CAS-416: Fix vote results for FLOAT

- frontend/packages/client/src/components/Community/CommunityEditorDetails/FormConfig.js
- frontend/packages/client/src/components/Community/CommunityEditorDetails/index.js
- frontend/packages/client/src/components/Community/ProposalThresholdEditor/FormConfig.js
- frontend/packages/client/src/hooks/useCommunity.js
> Fix typo on threshold

- backend/main/shared/ipfs.go
This reverts commit 4b390ed5f17b9fe24ed26b74fee2a028cef315ad.
> Revert "cas-404 bypass ipfs with dummy vals for local dev  (#338)"

- backend/main/models/strategy.go
- backend/main/models/vote.go
- backend/main/server/helpers.go
- backend/main/shared/ipfs.go
**Ticket:** [CAS-431](https://linear.app/dappercollectives/issue/CAS-431/add-function-to-check-for-nft-strategies)
> CAS-431: Add function to check for NFT strategy

- backend/main/server/helpers.go
* CAS-427: Fix Proposal restriction using NFT Contract
* CAS-427: Fix parse float bit size
Co-authored-by: Jonathan Bluks <jonathan.bluks@dapperlabs.com>
> CAS-427: Fix parseFloat bit size (#384)

- frontend/packages/client/src/components/Community/ProposalThresholdEditor/ProposalThresholdEditor.js
- frontend/packages/client/src/components/Community/StrategyEditorModal/StrategyInformationForm.js
- frontend/packages/client/src/pages/CommunityEditor.js
Fixes loading contractType value from backend when going to edit mode
> CAS-444 fix loading contract type on form edition

- backend/main/models/community.go
- contract type was missing from the UPDATE community query
> CAS-447: Add contractType to community update query

- frontend/packages/client/src/components/Community/ProposalThresholdEditor/ProposalThresholdEditor.js
Update text for the action button:
> CAS-436 Update action button to save

- frontend/packages/client/src/components/WalletConnectModal.js
- frontend/packages/client/src/contexts/Web3.js
> CAS-454 - Only use POP for DW connect

- backend/main/leaderboard_test.go
- backend/main/list_test.go
- backend/main/models/community_users.go
- backend/main/proposal_test.go
- backend/main/server/helpers.go
- backend/main/test_utils/community_user_utils.go
- backend/main/test_utils/community_utils.go
- backend/main/test_utils/proposal_utils.go
- backend/main/test_utils/vote_utils.go
- Fix test payloads that broke validateUser calls
- Fix Leaderboard bug with EarlyVote/Cancelled Proposal
> CAS-456: Fix broken tests

- backend/main/server/helpers.go
•fixes ipfs override. 
The override was made as I was getting the ipfs timeout error again
> fixed ipfs override

- frontend/packages/client/src/components/ProposalCreate/StepTwo.js
- frontend/packages/client/src/const/index.js
- frontend/packages/client/src/pages/ProposalCreate.js
- frontend/packages/client/src/utils.js
- Fixes time intervals set on dropdown for proposal creation. 
Before: 
After Fix:
To test locally set the env variable `REACT_APP_APP_ENV=production`
> CAS-464 - Fix start time intervals for proposal creation

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/FadeInOut.js
- frontend/packages/client/src/components/Svg.js
- frontend/packages/client/src/components/TooltipMessage.js
- frontend/packages/client/src/components/index.js
- frontend/packages/client/src/hooks/index.js
- frontend/packages/client/src/hooks/useBrowserName.js
- frontend/packages/client/src/hooks/useLocalStorage.js
- frontend/packages/client/src/pages/Home.js
CAS-467 - Add tooltip for DW Safari Users (#420)
* add icon
* create hook
* export element
* add hook
* add transition
* add transition
* add component
* update style
* update
* update
* add cursor pointer
* fix typo
> Staging -> Main

- frontend/packages/client/src/components/WalletConnectModal.js
> fix Lilico icon  (#441)

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Community/ProposalThresholdEditor/FormConfig.js
- frontend/packages/client/src/components/WalletConnect.js
- frontend/packages/client/src/components/WalletConnectModal.js
Added border rounded for wallet dropdown
> Fix border style

- frontend/packages/client/src/hooks/useJoinCommunity.js
- Adding signer addr to request. This field was dropped when refactoring to use react-query
> fix add missing field on adding/removing members

- frontend/packages/client/src/components/WalletConnect.js
Minor style change to make dropdown & button fit on screen
> CAS 150 - fix connect wallet dropdown style

- backend/main/cadence/scripts/custom/get_nba_topshot.cdc
- backend/main/cadence/scripts/custom/scripts.json
- Test script updated to support some test NBA TopShots
> Update Topshot script to Detroit Pistons

- frontend/packages/client/src/components/SideNavbar.js
Update on create a community text
> CAS-514 - Update text

- frontend/packages/client/src/App.sass
not sure how this got messed up but this value should be #F9F9F9. this color is also used for the box shadow on tables but I couldnt eyeball the difference so I think its OK to use there too. otherwise can add another shade for table box shadows
> update light grey

- backend/main/cadence/transactions/mint_nft.cdc
- backend/main/models/vote.go
- backend/main/strategies/balance_of_nfts.go
- backend/main/strategies/custom_script.go
- backend/main/strategies/float_nfts.go
- backend/main/strategies_test.go
- backend/main/test_utils/list_utils.go
- backend/main/test_utils/proposal_utils.go
- Correctly compute vote weight in `GetVoteWeightForBalance` for NFT strategies
- Call `GetVoteWeightForBalance` in `TallyVotes` for NFT strategies
- Fix tests
> CAS-534: bugfix for Max weight not enforced in voting

- backend/main/server/controllers.go
- backend/main/server/helpers.go
- Updates helper to handle different error conditions and return the correct status
> CAS-520: Fix error code return when creating a proposal

- backend/main/cadence/scripts/custom/get_nfl_all_day_legendary.cdc
- backend/main/cadence/scripts/custom/scripts.json
• Adds custom script for NFL All Day Contract Matching all `Legendary` editions
I used this repo https://github.com/rvmelkonian/nfl-overflow to test the script
> rich/cas-503 NFL All Day custom script

- frontend/packages/client/src/components/Header.js
- frontend/packages/client/src/components/SideNavbar.js
- frontend/packages/client/src/pages/BrowseCommunities.js
- frontend/packages/client/src/pages/Home.js
- frontend/packages/client/src/pages/index.js
> CAS-524 - Add "Browse" to homepage

- frontend/packages/client/src/components/Community/CommunityEditorProfile/CommunityEditorProfile.js
- frontend/packages/client/src/components/ProposalInformation/BlockieWithAddress.js
- frontend/packages/client/src/components/ProposalInformation/InfoBlock.js
- frontend/packages/client/src/components/ProposalInformation/Information.js
- frontend/packages/client/src/components/ProposalInformation/Results.js
- updated title font-size.
- fixed alignment 
- padding changes
> cas 574 - Style updates for proposal results & information

- backend/main/server/controllers.go
- backend/main/server/helpers.go
•fixed type cast error on search endpoint
> bugfix search

- backend/main/models/proposal.go
- backend/main/models/proposal_results.go
- backend/main/models/strategy.go
- backend/main/models/vote.go
- backend/main/shared/structs.go
- backend/main/strategies/tally_methods.go
- backend/main/strategies/tally_methods_test.go
- backend/tests/leaderboard_test.go
- backend/tests/test_utils/leaderboard_utils.go
- backend/tests/test_utils/vote_utils.go
- backend/tests/vote_test.go
- frontend/packages/client/src/api/proposals.js
- frontend/packages/client/src/components/ProposalInformation/ProposalInformation.js
- frontend/packages/client/src/components/ProposalInformation/Results.js
- frontend/packages/client/src/components/ProposalInformation/ResultsPanel.js
- frontend/packages/client/src/hooks/useVoteOnProposal.js
- frontend/packages/client/src/pages/Proposal.js
- Set ID on proposal Choices
- Store choice ID when creating vote on FE
- Use choice ID to calculate and display proposal results
- update affected tests
> CAS-580: Vote/Proposal Choices Refactor

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/BrowseCommunityButton.js
- frontend/packages/client/src/components/Community/CommunitiesPresenter.js
- frontend/packages/client/src/components/Community/CommunityCard.js
- frontend/packages/client/src/components/Community/CommunityCard/CommunityCard.js
- frontend/packages/client/src/components/Community/CommunityCard/NameAndBody.js
- frontend/packages/client/src/components/Community/CommunityCard/PillsWithStatus.js
- frontend/packages/client/src/components/Community/CommunityCard/index.js
- frontend/packages/client/src/components/Community/CommunityEditorProfile/CommunityEditorProfile.js
- frontend/packages/client/src/components/Header.js
- frontend/packages/client/src/components/HomeFooter.js
- frontend/packages/client/src/components/HomeHeader.js
- frontend/packages/client/src/components/ProposalInformation/ResultsPanel.js
- frontend/packages/client/src/components/StatusPill.js
- frontend/packages/client/src/components/index.js
- frontend/packages/client/src/layout/SectionContainer.js
- frontend/packages/client/src/pages/Home.js
Also updated to enable show upcoming and active proposals:
Mobile:
Designs: https://www.figma.com/file/bni5O6c7Yh1rCUwFRO8f9i/CAST%3A-Design-Library?node-id=262%3A12394
> CAS-583: Update Community Card Style

- frontend/packages/client/src/components/WalletConnectModal.js
> CAS-619: Allow FCL services to show on modal

- frontend/packages/client/src/components/Proposal/VoteOptions/TextBasedOptions.js
- frontend/packages/client/src/components/Proposal/VoteOptions/VoteHeader.js
- frontend/packages/client/src/components/Proposal/VoteOptions/VoteOptions.js
- frontend/packages/client/src/hooks/useCommunitySearch.js
- frontend/packages/client/src/pages/Proposal.js
- hides vote button on closed and proposals where user has voted: 
Upcoming proposals will have button disabled:
On closed ones:
> Fix proposal voting pannel

- frontend/packages/client/src/components/Proposal/VoteOptions/TextBasedOptions.js
- frontend/packages/client/src/components/Proposal/VoteOptions/VoteHeader.js
- frontend/packages/client/src/components/Proposal/VoteOptions/VoteOptions.js
- frontend/packages/client/src/hooks/useCommunitySearch.js
- frontend/packages/client/src/pages/Proposal.js
* remove output
* update header props
* hide vote buttton on proposal closed or complete
* remove opacity on pending or closed proposals
* remove comment
* update css prop
* remove read only
> Fix proposal voting pannel (#596)

- frontend/packages/client/src/components/Community/CommunityPropsAndVoting.js
- frontend/packages/client/src/components/Community/StrategySelectorForm.js
- This PR will enable deleting a single strategy and add a new one or the same one with different params. 
Targeting `release-v1.5.0` branch once branch to target is determined ( could be a hotfix `release-v1.4.6`)
> CAS-622: Fix Strategy update 

- frontend/packages/client/src/hooks/useCommunityDetailsUpdate.js
HOTFIX: include voucher in updateCommunity API req (#598)
> Release v1.4.6 -> main

- backend/main/models/community.go
- backend/main/server/controllers.go
- backend/main/server/helpers.go
- backend/tests/community_test.go
•fixes bug where total records was not updating the correct number when filters were applied.
> CAS-626 total records should update with the filter

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Proposal/VoteOptions/TextBasedOptions.js
- frontend/packages/client/src/components/Proposal/VoteOptions/VoteOptions.js
> CAS-628: Fix Proposal Preview text

- frontend/packages/client/src/components/ProposalCard/ProposalCardFooter.js
> CAS-627: Fix proposal card status

- frontend/packages/client/src/components/ProposalInformation/Information.js
- frontend/packages/client/src/components/ProposalInformation/ProposalInformation.js
Proposal Details table lists a 'Max Tokens' and 'Min Tokens' property that should be displayed as '... Weight'.
> CAS-635: Update Proposal Details fields

- frontend/packages/client/src/components/CommunityProposals.js
- Updates the proposals page drop-down menu options to use the new status labels.
Upcoming (instead of Pending)
Complete (instead of Closed)
Canceled (instead of Cancelled)
> CAS-634: Update proposal drop-down options

- frontend/packages/client/src/components/Proposal/HeaderNavigation.js
- frontend/packages/client/src/components/Proposal/ShareDropdown.js
- frontend/packages/client/src/pages/Proposal.js
> CAS-636: Update share twitter text

- backend/main/models/community.go
- backend/main/server/controllers.go
- backend/main/server/helpers.go
- backend/main/shared/structs.go
•fixes totalRecords and next -1 bug
> updated sql and logic for totalRecords and next

- frontend/packages/client/src/components/ProposalInformation/Information.js
- frontend/packages/client/src/pages/Proposal.js
Fix missing props and hardcoded value
> CAS-638: Fix missing props

- backend/main/models/proposal.go
- backend/tests/test_utils/proposal_utils.go
- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Proposal/VoteOptions/TextBasedOptions.js
- frontend/packages/client/src/components/ProposalCreate/FormConfig.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/ChoiceOptionCreator.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/TextBasedChoices.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/index.js
- frontend/packages/client/src/components/common/Input.js
- frontend/packages/client/src/components/modals/Error.js
- frontend/packages/client/src/components/modals/Modal.js
- frontend/packages/client/src/hooks/useProposalCreateMutation.js
- frontend/packages/client/src/pages/ProposalCreate.js
Adds a new section to the create proposal page for "Vote Type" which will currently be either Single Choice or Rank Voting
> CAS-611: Add Vote Type to Create Proposal

- backend/main/models/community.go
Adds the similarity score to the query so the search results can be ordered by the most relevant matching communities.
> Order Search by Similarity Score

- backend/main/models/community.go
Fixes query to work when filters are applied.
> Order Search based on similarity

- backend/main/models/community.go
- backend/tests/community_test.go
- frontend/packages/client/src/components/ProposalInformation/Information.js
•fixes merge conflicts
- Tests passing
> merge `release-v1.5.0` into `release-v1.6.0`

- frontend/packages/client/src/components/ProposalCreate/StepOne/RankedVoteExample.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/SingleVoteExample.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/VotingSelector.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/index.js
- extracted into component to reuse in https://github.com/DapperCollectives/CAST/pull/651
> extract into component

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/ProposalCreate/FormConfig.js
- frontend/packages/client/src/components/ProposalCreate/Preview.js
- frontend/packages/client/src/components/ProposalCreate/StepOne/index.js
- frontend/packages/client/src/components/ProposalCreate/StepThree/StepThree.js
- frontend/packages/client/src/components/ProposalCreate/StepTwo/ChoiceOptionCreator.js
- frontend/packages/client/src/components/ProposalCreate/StepTwo/StepTwo.js
- frontend/packages/client/src/components/ProposalCreate/StepTwo/TextBasedChoices.js
- frontend/packages/client/src/components/ProposalCreate/index.js
- frontend/packages/client/src/components/StepByStep/LeftPanel.js
- frontend/packages/client/src/components/StepByStep/NavStepByStep.js
- frontend/packages/client/src/components/StepByStep/StepLabelAndIcon.js
- frontend/packages/client/src/components/StepByStep/index.js
- frontend/packages/client/src/components/StyledStatusPill.js
- frontend/packages/client/src/components/common/Form.js
- frontend/packages/client/src/const/index.js
- frontend/packages/client/src/pages/ProposalCreate.js
Adds preview mode, once the user reaches Step 2 or Step 3 the preview button will become available. 
When the user clicks the button the preview mode should open. 
Only sections that have been completed are visible in the preview mode.
On mobile:
> CAS-608: CAP Preview

- frontend/packages/client/src/utils.js
- Update time check for proposal submission
> CAS-700: update start time check on proposal creation 

- frontend/packages/client/src/App.sass
- frontend/packages/client/src/components/Card/styles.js
- frontend/packages/client/src/components/StepByStep/StepByStep.sass
- frontend/packages/client/src/components/StepByStep/index.js
- Change border line in vote option hover:
- Remove left panel on preview mode in desktop 
- Update padding on tablet
> CAS-704: Update create proposal styles

- backend/main/server/app.go
- backend/main/server/helpers.go
- backend/main/shared/flow.go
- backend/main/strategies/total_token_weighted_default.go
- backend/migrations/000042_add_staked_token_strategy.up.sql
- backend/migrations/000042_add_total_token_strategy.down.sql
v1.9.2 is now in production and as per this [step](https://www.notion.so/CAST-Release-Process-4f65ad8a8e4d4982948017a423e7e2b0?pvs=4#2e4fca67a2184d09955cddb676f7808c), I am now merging it into main.
> Release-v1.9.2 → main

- backend/main/server/app.go
- backend/main/server/helpers.go
- backend/main/shared/flow.go
- backend/main/strategies/total_token_weighted_default.go
- backend/migrations/000042_add_staked_token_strategy.up.sql
- backend/migrations/000042_add_total_token_strategy.down.sql
Adds new total token balance strategy ( which includes staked / locked and main balance ) for FlowToken
> Total Token Strategy ( staked / locked / primary ) 
